name: products
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  http: ^1.2.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  dio: ^5.4.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
